name: CI
on: push
jobs:
  pytest:
      runs-on: ubuntu-latest
      container:
        image: aaherzing/tomotools:latest
      steps:
      - uses: actions/checkout@v3
      - run: conda info --envs
      - run: activate tomo
