name: CI
on: push
jobs:
  format-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install flake8
      - run: pip install pydocstyle
      - run: flake8 --exclude=api.py --ignore=E501 tomotools/
      - if: always()
        run: pydocstyle tomotools/

  pytest:
    runs-on: ubuntu-latest
    container:
      image: aaherzing/tomotools:latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install -e ./
    - run: pytest --doctest-modules --ignore=tomotools/tests/test_datasets.py tomotools/ 
    - if: always()
      run: pytest --ignore=tomotools/tests/test_datasets.py tomotools/tests/
